---
title:               Brett Bergmann
tagline:             Thanks for stopping by. I'll keep this brief.
login:               <%= ENV["obtvse_login"] ? ENV["obtvse_login"] : "username" %>
password:            <%= ENV["obtvse_password"] ? ENV["obtvse_password"] : "password" %>
name:                Brett Bergmann
twitter:             brttb
email:               me@brettbergmann.com
google_analytics_id: YOUR_GA_ID